const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,selected='',view='map',zoom=1,last='',first=true;
const lookup=id=>data.nodes.find(n=>n.id===id),pct=n=>n.checks.length?Math.round(100*n.checks.filter(c=>c.done).length/n.checks.length):0;
function state(n){if(['done','active','blocked','future'].includes(n.status))return n.status;return n.deps.every(d=>lookup(d)?.status==='done')?'ready':'locked';}
const labels={done:'已完成',active:'进行中',blocked:'受阻',future:'未来候选',ready:'可开始',locked:'待解锁'};
function renderShell(){
 const p=data.project;
 document.title=`${p.name} · 项目路线图`;$('#logo').textContent=p.shortName;$('#project-icon').textContent=p.shortName;$('#brand-name').textContent=p.name;$('#project-name').textContent=p.name;$('#project-context').textContent=p.context;$('#eyebrow').textContent=p.eyebrow;$('#page-title').textContent=p.headline;$('#version-label').textContent=p.versionLabel;
 $('#documents').innerHTML=data.documents.map(d=>`<a href="/doc?path=${encodeURIComponent(d.path)}" target="_blank">↗　${esc(d.label)}</a>`).join('');
 const {width,height}=data.canvas;$('#scene').style.width=`${width}px`;$('#scene').style.height=`${height}px`;$('#edges').setAttribute('width',width);$('#edges').setAttribute('height',height);$('#edges').style.width=`${width}px`;$('#edges').style.height=`${height}px`;
}
function render(){
 if(!selected||!lookup(selected))selected=data.nodes[0]?.id||'';renderShell();
 const required=data.nodes.filter(n=>n.status!=='future'),done=required.filter(n=>n.status==='done').length,passed=data.acceptance.filter(a=>a.passed).length;
 $('#stats').innerHTML=[['✓',`${done} <span style="font-size:13px;color:#9aa8bc">/ ${required.length}</span>`,'开发节点已完成'],['◉',required.filter(n=>n.status==='active').length,'节点进行中'],['◇',required.filter(n=>state(n)==='ready').length,'前置满足 · 可开始'],['☷',`${passed} <span style="font-size:13px;color:#9aa8bc">/ ${data.acceptance.length}</span>`,'正式验收通过']].map(([s,v,l])=>`<div class="stat"><div class="stat-symbol">${s}</div><div><strong>${v}</strong><small>${l}</small></div></div>`).join('');
 $('#stages').innerHTML=data.stages.map(s=>`<div class="stage" style="top:${s.y}px;width:${data.canvas.width-40}px"><b>${esc(s.title)}</b><p>${esc(s.subtitle)}</p></div>`).join('');
 $('#nodes').innerHTML=data.nodes.map(n=>`<button class="node ${state(n)} ${n.id===selected?'selected':''}" data-node="${esc(n.id)}" style="left:${n.x}px;top:${n.y}px" aria-label="${esc(n.title)}，${labels[state(n)]}" aria-pressed="${n.id===selected}"><span class="symbol">${({done:'✓',active:'◎',future:'✧',blocked:'!'}[state(n)]||'◇')}</span><div><strong>${esc(n.title)}</strong><small>${esc(n.subtitle)}</small>${n.status==='active'?`<div class="bar"><i style="width:${pct(n)}%"></i></div>`:''}</div><span class="state-mark">${state(n)==='done'?'✓':state(n)==='locked'?'⌑':state(n)==='ready'?'○':''}</span></button>`).join('');
 $('#edges').innerHTML='<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#9eafca"/></marker></defs>'+data.nodes.flatMap(n=>n.deps.map(id=>{const a=lookup(id),sx=a.x+113,sy=a.y+82,tx=n.x+113,ty=n.y;return `<path d="M${sx},${sy} C${sx},${sy+(ty-sy)/2} ${tx},${sy+(ty-sy)/2} ${tx},${ty-5}" fill="none" stroke="${n.id===selected?'#7b9fff':'#b4c2d7'}" stroke-width="1.2" ${n.status==='future'?'stroke-dasharray="5 5"':''} marker-end="url(#arrow)"/>`;})).join('');
 const mapped=new Set(data.nodes.flatMap(n=>n.ac));
 $('#acceptance-view').innerHTML=`<h2>正式验收清单 <span class="badge">${passed} / ${data.acceptance.length}</span></h2><p class="info">直接同步 ${esc(data.acceptanceSource||'配置的验收文件')}。开发检查点与正式验收分别统计；用例通过前需保存规定环境和证据。</p>`+(data.acceptance.length?data.acceptance.map(a=>`<article class="case"><h3>${a.passed?'✓':'○'} ${esc(a.id)} <span class="badge">${esc(a.level)}</span></h3><small>${esc(a.requirement)} · ${a.passed?'已通过':'未验收'}${mapped.has(a.id)?'':' · 待关联节点'}</small><p>${esc(a.action)}</p><p><b>通过标准：</b>${esc(a.criteria)}</p></article>`).join(''):'<p class="empty">该项目尚未配置正式验收清单。</p>');
 $('#activity-view').innerHTML='<h2>开发记录</h2><p class="info">以项目状态文件中的记录为准；不是自动推断的提交历史。</p>'+data.activity.map(a=>`<article class="event"><small>${esc(a.date)}</small><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p></article>`).join('');
 renderDetail();filter();
}
function dep(n){return `<button class="dep" data-node="${esc(n.id)}"><span>${n.status==='done'?'✓':'○'}　${esc(n.title)}</span><span>›</span></button>`;}
function renderDetail(){const n=lookup(selected);if(!n){$('#detail').innerHTML='<p class="empty">尚无路线节点。</p>';return;}const unlocked=data.nodes.filter(a=>a.deps.includes(n.id)),count=n.deps.filter(id=>lookup(id)?.status==='done').length;
 $('#detail').innerHTML=`<div class="detail-kicker">${esc(n.stage)} / ${esc(n.id.toUpperCase())}</div><h2>${esc(n.title)}</h2><span class="badge">${labels[state(n)]}</span><div class="progress"><i style="width:${pct(n)}%"></i></div><div class="progress-label"><span>开发检查点</span><span>${n.checks.filter(c=>c.done).length} / ${n.checks.length} · ${pct(n)}%</span></div><h4>节点目标</h4><p>${esc(n.description)}</p>${n.blocker?`<p class="info">受阻原因：${esc(n.blocker)}</p>`:''}<h4>完成条件</h4>${n.checks.map(c=>`<div class="check"><em class="${c.done?'passed':''}">${c.done?'●':'○'}</em><span>${esc(c.text)}</span></div>`).join('')}<h4>前置条件 <span class="quiet">${count} / ${n.deps.length} 已满足 · AND</span></h4>${n.deps.length?n.deps.map(id=>dep(lookup(id))).join(''):'<span class="empty">起始节点，无前置条件</span>'}<h4>${n.status==='future'?'后续路线':'完成后推进'}</h4>${unlocked.length?unlocked.map(dep).join(''):'<span class="empty">当前路线终点</span>'}<h4>关联正式验收</h4>${n.ac.length?n.ac.map(id=>{const a=data.acceptance.find(a=>a.id===id);return `<button class="dep" data-case="${esc(id)}"><span>${esc(id)}</span><span>${a?.passed?'已通过':'未验收'} ›</span></button>`;}).join(''):'<p class="empty">本节点未关联正式验收。</p>'}<h4>证据与参考</h4>${n.evidence.length?n.evidence.map(f=>`<a class="doc" target="_blank" href="/doc?path=${encodeURIComponent(f)}">↗ ${esc(f)}</a>`).join(''):'<span class="empty">尚无证据文件。</span>'}<p class="info">状态随项目文件同步。页面不会根据文件存在、构建成功或 Mock 结果推断产品通过。</p>`;
}
function filter(){const q=$('#search').value.toLowerCase();document.querySelectorAll('.node').forEach(el=>{const n=lookup(el.dataset.node);el.classList.toggle('dim',q&&!`${n.title} ${n.subtitle} ${n.id} ${n.ac.join(' ')} ${data.acceptance.filter(a=>n.ac.includes(a.id)).map(a=>a.requirement).join(' ')}`.toLowerCase().includes(q));});}
function switchView(v){view=v;for(const name of ['map','acceptance','activity'])$(`#${name}-view`).hidden=v!==name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));}
function setZoom(z){zoom=Math.max(.35,Math.min(1.6,z));$('#scene').style.zoom=zoom;$('#scale').textContent=Math.round(zoom*100)+'%';}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]'),n=e.target.closest('[data-node]'),a=e.target.closest('[data-case]');if(v)switchView(v.dataset.view);if(n){selected=n.dataset.node;switchView('map');render();document.querySelector(`.node[data-node="${CSS.escape(selected)}"]`)?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'});}if(a){switchView('acceptance');const index=data.acceptance.findIndex(c=>c.id===a.dataset.case);$('#acceptance-view').querySelectorAll('.case')[index]?.scrollIntoView({block:'start',behavior:'smooth'});}});
$('#search').addEventListener('input',filter);$('#plus').onclick=()=>setZoom(zoom+.1);$('#minus').onclick=()=>setZoom(zoom-.1);$('#fit').onclick=()=>{setZoom(Math.min(1,($('#viewport').clientWidth-12)/data.canvas.width));$('#viewport').scrollTo(0,0);};
$('#export').onclick=()=>{if(!data)return;const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=`${data.project.name}-roadmap.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
async function sync(){try{const r=await fetch('/api/state');if(!r.ok)throw Error();const next=await r.text(),parsed=JSON.parse(next);if(!Array.isArray(parsed.nodes))throw Error();if(next!==last){data=parsed;render();last=next;}$('#sync').textContent='● 已同步 · '+new Date().toLocaleTimeString('zh-CN',{hour12:false});if(first){first=false;$('#fit').click();}}catch{$('#sync').textContent='○ 同步失败 · 保留上次视图';}finally{setTimeout(sync,2000);}}sync();
